### ISSUE TITLE
PHP 8.0 support

### ISSUE THREAD

**Issue by devrzaph** [illuusio/pecl-php-blenc#3]
Hello how are you?

First of all, thank you for keeping this project active, the legacies appreciate it.

---------

I'm having trouble compiling the PHP 8.0 extension, funny that 8.1 is ok.

```
/home/user/PhpstormProjects/GitHub/pecl-php-blenc/blenc.c: In function ‘blenc_compile’:
/usr/include/php/20200930/Zend/zend_string.h:60:31: error: request for member ‘val’ in something not a structure or union
   60 | #define ZSTR_VAL(zstr)  (zstr)->val
      |                               ^~
/home/user/PhpstormProjects/GitHub/pecl-php-blenc/blenc.c:598:14: note: in expansion of macro ‘ZSTR_VAL’
  598 |  file_name = ZSTR_VAL(file_handle->filename);
      |              ^~~~~~~~
make: *** [Makefile:208: blenc.lo] Error 1
```
Line in question:

```
#ifdef PHP_ZEND_ENGINE_8_0
	file_name = ZSTR_VAL(file_handle->filename);
#endif
````

I looked at other projects, and they work this way with the file_handle pointer, could you help me with this?

Grateful.

**Comment by devrzaph** [comment]
I did some more tests, if I only use:

`file_name = file_handle->filename;`

rather than

`ifdef PHP_ZEND_ENGINE_8_0 file_name = ZSTR_VAL(file_handle->filename); #endif`

For me it worked correctly in PHP 8.0.26, I just don't have the knowledge to know the impact of this change.

What do you think?

**Comment by illuusio** [comment]
Thank you for but report and suggestion. Which distro do you use for compiling?

**Comment by devrzaph** [comment]
Ubuntu 20.04.5 LTS

Linux 5.15.0-56-generic

PHP 8.0.26 (cli)

PHP Api Version: 20200930

**Comment by illuusio** [comment]
Ok thanks for the info. Focal (20.04) does have only PHP 7.4 (or am I missing something?).Do you use that PPA which is providing PHP 8.x packages? Just asking that I can add this on Actions and test it in future until it's EOL'd next year. It seems that PHP 8.2 has some changes that needs to be observed also.

**Comment by illuusio** [comment]
There is now Pull request PR #4  to review and test. PHP 8.2 support is just for the kicks and it needs love to make it work correctly. So if you are using PHP 8.0. Then 8.1 works but 8.2 has issues

**Comment by marcosmarcolin** [comment]
@devrzaph @illuusio I've been going through the same problem, I'll get involved and try to help too.

**Comment by illuusio** [comment]
@marcosmarcolin thank you for getting in! if you have time please test PR if it's fixing your problem. PHP 8.0 and 8.1 should work as expected but please remember **PHP 8.2 needs some :heart: (they changes drastically how loading works) and I'll need to figure can I get old behavior back. It's something that will break thinks**.

**Comment by marcosmarcolin** [comment]
@illuusio I believe I have the solution for PHP 8.2, can you grant me permission to publish to your PR branch? I don't have permission to branch this repository.

If not, I will make a Fork and request a PR here, however, it will conflict with your PR.

**Comment by Girgias** [comment]
So @marcosmarcolin emailed me to review his PR, and seeing that this extension does some *ancient* stuff I decide to do some clean up and performance optimizations.

Can be found in #6

**Comment by illuusio** [comment]
I'm kind of stunned that in something like 7-10 years that I've been maintaining this for myself there is this much attraction. Very good and thanks for the PR @Girgias  and @marcosmarcolin. I'll see the both and try to settle on #6 I think.


> does some _ancient_ stuff I decide to do some clean up and performance optimizations.

Ancient stuff comes from PHP 5.3 or even more far away. I've been cleaning it but tried to keep kind of untouch as I'm just a guy from bus station how happens to need this extension type of maintainer.

**Comment by illuusio** [comment]
> If not, I will make a Fork and request a PR here, however, it will conflict with your PR.

No problem. I'll see the changes as said above.

**Comment by illuusio** [comment]
As I was lazy and thought that it'se easier to review remove of those macros in own PR. I opened pr #9 which removes some old crust in code. They wanted to go so when it lands they go away. @marcosmarcolin  and @Girgias if you could look at them (it's based on @Girgias work) and I'll merge them. As I see that @Girgias  pointed very good things but they should be Ironed out as we can see what really needs to be changed to get PHP 8.x support as good as it gets

**Comment by marcosmarcolin** [comment]
@Girgias Thank you for your help and quick response, this type of work makes a difference for our community. Your work impacts the lives of many people who depend on PHP and you already know that, congratulations.

@illuusio Your work during these years has been very important, congratulations. I got involved because I depend on this extension in personal projects, I have a modified solution that I maintain and develop in a proprietary repository. So I decided to support this project with my little knowledge. I'll be available for whatever you need, just contact me. I'm happy to be able to help.

**Comment by devrzaph** [comment]
Thank you for your personal help and for my suggestion. I will end this discussion.

**Comment by illuusio** [comment]
Now it's officially on release candidate please test @devrzaph
